version: '3.8'

services:
  app:
    build: .
    image: my-app:latest
    container_name: my-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app